create table if not exists public.categories (
  key text primary key,
  label text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_key text not null references public.categories(key) on update cascade,
  sort_order integer not null default 1,
  is_visible boolean not null default true,
  is_soon boolean not null default false,
  price integer not null default 0,
  old_price integer not null default 0,
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  description text not null default '',
  stock text not null default '',
  variants jsonb not null default '[]'::jsonb,
  badge text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint products_badge_check check (badge is null or badge in ('new', 'hot'))
);

create table if not exists public.orders (
  id bigint primary key,
  status text not null default 'new',
  created_at timestamptz not null default timezone('utc', now()),
  source text not null default 'miniapp',
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  total integer not null default 0,
  raw_text text not null default '',
  telegram jsonb not null default '{}'::jsonb,
  request_meta jsonb not null default '{}'::jsonb,
  constraint orders_status_check check (status in ('new', 'processing', 'done', 'cancelled'))
);

create table if not exists public.customers (
  key text primary key,
  telegram_id text not null default '',
  name text not null default '',
  phone text not null default '',
  username text not null default '',
  delivery text not null default '',
  comment text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.promo_banners (
  id bigint generated by default as identity primary key,
  title text not null,
  kicker text not null default '',
  image text not null default '',
  cta_label text not null default '',
  secondary_label text not null default '',
  sort_order integer not null default 1,
  is_active boolean not null default true,
  action_type text not null default 'reset',
  action_value text not null default '',
  secondary_action_type text not null default '',
  secondary_action_value text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint promo_banners_action_type_check check (action_type in ('reset', 'category', 'product', 'link')),
  constraint promo_banners_secondary_action_type_check check (secondary_action_type in ('', 'reset', 'category', 'product', 'link'))
);

create index if not exists products_category_key_idx on public.products (category_key);
create index if not exists products_sort_order_idx on public.products (sort_order, id);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists customers_phone_idx on public.customers (phone);
create index if not exists customers_username_idx on public.customers (username);
create index if not exists customers_updated_at_idx on public.customers (updated_at desc);
create index if not exists promo_banners_sort_order_idx on public.promo_banners (sort_order, id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
before update on public.customers
for each row
execute function public.set_updated_at();

drop trigger if exists promo_banners_set_updated_at on public.promo_banners;
create trigger promo_banners_set_updated_at  
before update on public.promo_banners
for each row
execute function public.set_updated_at();



